easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Instytucja
        - App\Entity\Kierunek
        - App\Entity\Literatura
        - App\Entity\Program
        - App\Entity\Semestr
        - App\Entity\Sylabus
        - App\Entity\Uzytkownik
        - App\Entity\Zajecia
