security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Uzytkownik
        property: login
  encoders:
    Symfony\Component\Security\Core\User\User: 'auto'
    App\Entity\Uzytkownik:
      algorithm: auto
  access_decision_manager:
    strategy: unanimous
    allow_if_all_abstain: false
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: default


  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
      # the 'path' value can be any valid regular expression
      # (this one will match URLs like /api/post/7298 and /api/comment/528491)
#      - { path: ^/api/(post|comment)/\d+$, roles: ROLE_USER }
